server.port=8761

spring.application.name=discovery-server

# Bu servis kendine kayit olmasin
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka dashboard aktif
eureka.server.enable-self-preservation=false

logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF