server.port=8080
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Gateway Routes

# JWT
jwt.secret=ecommerce_super_secret_key_2024_must_be_at_least_256_bits_long

# CORS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*

logging.level.org.springframework.cloud.gateway=DEBUG