server.port=8888

spring.application.name=config-server

# Native mod: config dosyalar? proje içinde classpath'te tutaca??z
# Git repo yerine local klasör kullan?yoruz (ödev için yeterli)
spring.cloud.config.server.native.search-locations=classpath:/configs

spring.profiles.active=native

# Eureka'ya kay?t ol
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true